'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Capacitor} from '@capacitor/core';
import {Geolocation} from '@capacitor/geolocation';
import dynamic from 'next/dynamic';
import {ExternalStore,FamilySource,FAMILY_SOURCE,PUBLIC_AREA,PUBLIC_AREAS,QueryArea,SourceResult,isStale} from '../lib/familymart';
const LiveMap=dynamic(()=>import('./LiveMap'),{ssr:false});
const displayTime=(value:string|null)=>value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'未知';
export default function ConvenienceApp({embedded=false,nearbyCenter,onStores}:{embedded?:boolean;nearbyCenter?:[number,number]|null;onStores?:(stores:ExternalStore[])=>void}={}){
 const source=useRef<FamilySource|null>(null),sources=useRef(new Map<string,FamilySource>()),generation=useRef(0),[area,setArea]=useState<QueryArea>(PUBLIC_AREA),[consent,setConsent]=useState(false),[locating,setLocating]=useState(false),[locationMessage,setLocationMessage]=useState(''),[result,setResult]=useState<SourceResult|null>(null),[busy,setBusy]=useState(false),[filter,setFilter]=useState(''),[selected,setSelected]=useState(''),[mapVisible,setMapVisible]=useState(false),[clock,setClock]=useState(Date.now());
 function chooseArea(next:QueryArea){
  generation.current++;setBusy(false);setLocating(false);setConsent(false);setArea(next);setFilter('');setSelected('');setMapVisible(false);
  let cached=sources.current.get(next.id);
  if(!cached){let storage:Storage|undefined;if(!next.nearby)try{storage=localStorage;}catch{}cached=new FamilySource(storage,undefined,Date.now,next);if(!next.nearby)sources.current.set(next.id,cached);}
  source.current=cached;setResult(cached.current());return generation.current;
 }
 useEffect(()=>{chooseArea(PUBLIC_AREA);const tick=setInterval(()=>setClock(Date.now()),60000);return()=>{generation.current++;clearInterval(tick);};},[]);
 async function query(){if(busy||!source.current)return;const token=generation.current,current=source.current;setBusy(true);try{const next=await current.query();if(token===generation.current)setResult(next);}finally{if(token===generation.current)setBusy(false);}}
 async function locate(){
  if(locating)return;const token=++generation.current;setBusy(false);setConsent(false);setLocating(true);setLocationMessage('正在取得位置；可取消或手動選地區。');
  try{
   const native=Capacitor.isNativePlatform();
   if(native){const permission=await Geolocation.requestPermissions();if(permission.location!=='granted'&&permission.coarseLocation!=='granted')throw {code:1};}
   if(token!==generation.current)return;
   const position=native?await Geolocation.getCurrentPosition({enableHighAccuracy:false,timeout:10000}):await new Promise<GeolocationPosition>((resolve,reject)=>{if(!navigator.geolocation)return reject({code:2});navigator.geolocation.getCurrentPosition(resolve,reject,{timeout:10000,maximumAge:0,enableHighAccuracy:false});});
   if(token!==generation.current)return;
   const {latitude,longitude}=position.coords;if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)throw {code:2};
   const next={id:'nearby-session',name:'本次同意的附近位置',latitude,longitude,nearby:true};const requestToken=chooseArea(next);setLocationMessage('已取得位置，正向全家查詢；位置與附近快取僅留在本頁記憶體。');setBusy(true);
   const response=await source.current!.query();if(requestToken===generation.current){setResult(response);setBusy(false);}
  }catch(error){if(token!==generation.current)return;const code=(error as {code?:number|string})?.code;setLocationMessage(code===1||code==='OS-PLUG-GLOC-0003'?'未允許定位，未傳送座標。請手動選地區。':'定位未成功或服務關閉，未傳送座標。請手動選地區。');}
  finally{if(token===generation.current)setLocating(false);}
 }
 useEffect(()=>{if(!embedded||!nearbyCenter)return;const next={id:'nearby-session',name:'本次同意的附近位置',latitude:nearbyCenter[0],longitude:nearbyCenter[1],nearby:true};const token=chooseArea(next);setBusy(true);source.current!.query().then(response=>{if(token===generation.current)setResult(response);}).finally(()=>{if(token===generation.current)setBusy(false);});},[nearbyCenter,embedded]);
 useEffect(()=>{onStores?.(result?.stores.map(s=>({...s,name:s.name+(isStale(s,result,clock)?'（舊資料或時間未知）':'')}))||[]);},[result,onStores,clock]);
 const stores=(result?.stores||[]).filter(s=>`${s.name} ${s.address}`.includes(filter.trim()));
 const selectedStore=stores.find(s=>s.id===selected)||stores[0];
 const count=(store:ExternalStore)=>store.quantity===null?'數量未知':`${store.quantity}份（來源回報）`;
 return <div className={embedded?'nearby-family':'app-shell live-app'}>{!embedded&&<header className="brand"><Link href="/" className="brand-title">食在可惜<small>超商惜食資訊</small></Link><span className="tag">免登入</span></header>}<div className={embedded?'':'page'}><h1>超商惜食資訊</h1><p>僅提供資訊，不能在此預約或核銷；商品與數量以現場為準。</p>
 <section className="card live-form"><h2>全家 友善食光</h2><p className="tag">友善食光・折扣商品</p><p className="tag">友善食光・符合條件享7折</p><p>官方規則：當日24時到期的適用鮮食，自17時起7折；部分17時到期商品自10時起適用。是否適用及金額以門市收銀機判讀為準。</p><p className="small">規則查核：2026-10-04；下方來源更新時間是庫存資訊時間，不是逐包折扣或效期證明。</p><p className="small">資料來自友善食光折扣專區；來源沒有逐包效期、折扣標記或折後價，同款商品不代表每包都適用折扣。</p><label>手動選擇公開地區<select aria-label="手動選擇公開地區" value={area.nearby?'':area.id} onChange={e=>{const next=PUBLIC_AREAS.find(a=>a.id===e.target.value);if(next){chooseArea(next);setLocationMessage('');}}}>{area.nearby&&<option value="" disabled>本次附近位置</option>}{PUBLIC_AREAS.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><p>查詢區域：{area.name}</p><p className="small">手選查詢僅傳送所選公開中心座標與一般連線資訊，不使用你的定位或FoodSave登入憑證。選項為區域中心，來源實際回傳範圍由全家決定，尚未驗證全台覆蓋。</p>{!embedded&&<button className="secondary" disabled={locating||busy} onClick={()=>setConsent(true)}>查詢我的附近</button>}{consent&&<section role="dialog" aria-label="附近查詢定位同意"><p>同意後才會請求系統定位權限，並將本次裝置經緯度及一般連線資訊傳送給全家（stamp.family.com.tw），用於附近門市查詢。FoodSave不保存定位歷程；本頁附近快取僅在記憶體，離頁後清除。不同意仍可手動選公開地區。</p><button className="primary" onClick={locate}>同意傳送位置並查詢</button><button className="secondary" onClick={()=>setConsent(false)}>取消</button></section>}{locating&&<button className="secondary" onClick={()=>{generation.current++;setLocating(false);setLocationMessage('已取消定位，不會傳送這次取得的座標。');}}>取消定位</button>}{locationMessage&&<p role="status">{locationMessage}</p>}<button className="primary" disabled={busy||locating} onClick={query}>{busy?'正在查詢來源…':area.nearby?'重新查詢本次附近':'查詢全家公開區域'}</button><p className="small">來源約每30分鐘更新，同區域查詢快取30分鐘。再次查詢不會連續向來源發送請求。</p><p role="status">{busy?'正在確認資料…':!result?.checkedAt?'尚未查詢。':result.status==='unavailable'?'全家來源暫時無法取得，庫存未知；請稍後再試。':result.cached?'顯示最近一次查詢快取。':'已取得來源回報，非即時保留。'}</p>{result?.checkedAt&&<><p className="small">最近查詢：{displayTime(result.checkedAt)}（台灣時間）</p><p className="small">下次可向來源更新：{displayTime(result.retryAt)}</p></>}{result?.status==='unavailable'&&result.stores.length>0&&<p role="alert">以下為上次成功查詢的舊資料，不能確認目前仍有庫存。上次成功：{displayTime(result.lastSuccessAt)}</p>}<a href={FAMILY_SOURCE} target="_blank" rel="noreferrer">全家友善食光官方說明</a></section>
 <section className="card"><h2>7‑ELEVEN i珍食</h2><p>庫存整合列為後續待辦，尚未完成庫存整合；沒有可確認的門市商品或數量。</p><p className="small">不以範例、全家資料或零庫存代替。</p><div className="row"><a className="secondary" href="https://www.7-11.com.tw/event/lovefood/index.aspx" target="_blank" rel="noreferrer">7‑ELEVEN 官方 i珍食介紹</a><a className="secondary" href="https://play.google.com/store/apps/details?id=tw.net.pic.m.openpoint" target="_blank" rel="noreferrer">前往 OPENPOINT 官方 App</a></div><p className="small">以上為官方查詢入口，非本App庫存整合，也不會直達指定門市庫存。</p></section>
 {!!result?.stores.length&&<><label className="live-form">篩選已查得店名或地址<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="只篩選目前區域，不傳送搜尋文字"/></label><button className="secondary" onClick={()=>setMapVisible(v=>!v)}>{mapVisible?'收起地圖':'顯示公開區域地圖'}</button><p className="small">地圖使用OpenStreetMap底圖，開啟後會連線至底圖服務；藍點是本次查詢中心；附近模式可能讓底圖服務推知位置區域，請自行決定是否開啟；地圖數字為來源回報合計，？表示未知。</p>{mapVisible&&<LiveMap key={area.id} center={[area.latitude,area.longitude]} stores={stores.map(s=>({id:s.id,name:'友善食光・折扣商品｜'+s.name+(result&&isStale(s,result,clock)?'（舊資料或時間未知）':''),lat:s.latitude,lng:s.longitude,count:s.quantity}))} onSelect={setSelected}/>}<div className="nearby-tabs">{stores.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} aria-pressed={s.id===selectedStore?.id}>{s.name} · 友善食光・折扣商品 · {count(s)}</button>)}</div>{!stores.length&&<p>目前查得門市中沒有符合的店名或地址。</p>}{selectedStore&&<section className="card"><h2>{selectedStore.name}</h2><p className="tag">友善食光・折扣商品</p><p>折扣與售價依門市結帳為準</p><p>{selectedStore.address}</p><p>來源更新：{displayTime(selectedStore.sourceUpdatedAt)}（台灣時間）</p>{result&&isStale(selectedStore,result,clock)&&<p className="tag">資料可能已變動或更新時間未知，請以現場為準</p>}<p className="small">來源未提供售價、照片或商品期限，本頁不補填。以下份數不包含分類合計的重複加總。</p>{selectedStore.products.length===0?<p>來源未回報商品明細，無法判定為零庫存。</p>:selectedStore.products.map(p=><article className="product" key={p.id}><div><h3>{p.name}</h3><p className="tag">友善食光・折扣商品</p><p>折扣與售價依門市結帳為準</p>{p.category&&<p>{p.category}</p>}<p>{p.quantity===null?'數量未知':`${p.quantity}份（來源回報）`}</p></div></article>)}</section>}</>}
 {result?.status==='ok'&&!result.stores.length&&<p>來源此次未回報此區域的門市資料；不代表所有門市售完。</p>}
 {!embedded&&<Link className="secondary" href="/">返回自營店家與攤販</Link>}<p><Link href="/privacy/">隱私與資料使用說明</Link></p></div>{!embedded&&<nav className="bottom-nav" aria-label="主要導覽"><Link href="/">自營店家</Link><Link className="active" href="/convenience/">超商資訊</Link><Link href="/profile/">個人中心</Link></nav>}</div>;
}
