'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {ExternalStore,FamilySource,FAMILY_SOURCE,PUBLIC_AREA,SourceResult,isStale} from '../lib/familymart';
const LiveMap=dynamic(()=>import('./LiveMap'),{ssr:false});
const displayTime=(value:string|null)=>value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'未知';
export default function ConvenienceApp(){
 const source=useRef<FamilySource|null>(null),[result,setResult]=useState<SourceResult|null>(null),[busy,setBusy]=useState(false),[filter,setFilter]=useState(''),[selected,setSelected]=useState(''),[mapVisible,setMapVisible]=useState(false),[clock,setClock]=useState(Date.now());
 useEffect(()=>{let storage:Storage|undefined;try{storage=localStorage;}catch{}source.current=new FamilySource(storage);setResult(source.current.current());const tick=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(tick);},[]);
 async function query(){if(busy||!source.current)return;setBusy(true);try{setResult(await source.current.query());}finally{setBusy(false);}}
 const stores=(result?.stores||[]).filter(s=>`${s.name} ${s.address}`.includes(filter.trim()));
 const selectedStore=stores.find(s=>s.id===selected)||stores[0];
 const count=(store:ExternalStore)=>store.quantity===null?'數量未知':`${store.quantity}份（來源回報）`;
 return <div className="app-shell live-app"><header className="brand"><Link href="/" className="brand-title">食在可惜<small>超商惜食資訊</small></Link><span className="tag">免登入</span></header><main className="page"><h1>超商惜食資訊</h1><p>僅提供資訊，不能在此預約或核銷；商品與數量以現場為準。</p>
 <section className="card live-form"><h2>全家 友善食光</h2><p>折扣以門市結帳為準。</p><p className="small">資料來自友善食光折扣專區；來源沒有逐包效期、折扣標記或折後價，同款商品不代表每包都適用折扣。</p><p>查詢區域：{PUBLIC_AREA.name}</p><p className="small">查詢會連到全家公開來源，傳送上述公開區域座標與一般連線資訊；不讀取或傳送你的定位、FoodSave帳號或登入憑證。</p><button className="primary" disabled={busy} onClick={query}>{busy?'正在查詢來源…':'查詢全家公開區域'}</button><p className="small">來源約每30分鐘更新，同區域查詢快取30分鐘。再次查詢不會連續向來源發送請求。</p><p role="status">{busy?'正在確認資料…':!result?.checkedAt?'尚未查詢。':result.status==='unavailable'?'全家來源暫時無法取得，庫存未知；請稍後再試。':result.cached?'顯示最近一次查詢快取。':'已取得來源回報，非即時保留。'}</p>{result?.checkedAt&&<><p className="small">最近查詢：{displayTime(result.checkedAt)}（台灣時間）</p><p className="small">下次可向來源更新：{displayTime(result.retryAt)}</p></>}{result?.status==='unavailable'&&result.stores.length>0&&<p role="alert">以下為上次成功查詢的舊資料，不能確認目前仍有庫存。上次成功：{displayTime(result.lastSuccessAt)}</p>}<a href={FAMILY_SOURCE} target="_blank" rel="noreferrer">全家友善食光官方說明</a></section>
 <section className="card"><h2>7‑ELEVEN i珍食</h2><p>官方庫存來源目前無法取得，尚未完成庫存整合；沒有可確認的門市商品或數量。</p><p className="small">不以範例、全家資料或零庫存代替。</p><div className="row"><a className="secondary" href="https://www.7-11.com.tw/event/lovefood/index.aspx" target="_blank" rel="noreferrer">7‑ELEVEN 官方 i珍食介紹</a><a className="secondary" href="https://play.google.com/store/apps/details?id=tw.net.pic.m.openpoint" target="_blank" rel="noreferrer">前往 OPENPOINT 官方 App</a></div><p className="small">以上為官方查詢入口，非本App庫存整合，也不會直達指定門市庫存。</p></section>
 {!!result?.stores.length&&<><label className="live-form">篩選已查得店名或地址<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="只篩選目前區域，不傳送搜尋文字"/></label><button className="secondary" onClick={()=>setMapVisible(v=>!v)}>{mapVisible?'收起地圖':'顯示公開區域地圖'}</button><p className="small">地圖使用OpenStreetMap底圖，開啟後會連線至底圖服務；藍點是公開查詢中心，不是你的定位；地圖數字為來源回報合計，？表示未知。</p>{mapVisible&&<LiveMap center={[PUBLIC_AREA.latitude,PUBLIC_AREA.longitude]} stores={stores.map(s=>({id:s.id,name:s.name,lat:s.latitude,lng:s.longitude,count:s.quantity}))} onSelect={setSelected}/>}<div className="nearby-tabs">{stores.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} aria-pressed={s.id===selectedStore?.id}>{s.name} · {count(s)}</button>)}</div>{!stores.length&&<p>目前查得門市中沒有符合的店名或地址。</p>}{selectedStore&&<section className="card"><h2>{selectedStore.name}</h2><p>{selectedStore.address}</p><p>來源更新：{displayTime(selectedStore.sourceUpdatedAt)}（台灣時間）</p>{result&&isStale(selectedStore,result,clock)&&<p className="tag">資料可能已變動或更新時間未知，請以現場為準</p>}<p className="small">來源未提供售價、照片或商品期限，本頁不補填。以下份數不包含分類合計的重複加總。</p>{selectedStore.products.length===0?<p>來源未回報商品明細，無法判定為零庫存。</p>:selectedStore.products.map(p=><article className="product" key={p.id}><div><h3>{p.name}</h3>{p.category&&<p>{p.category}</p>}<p>{p.quantity===null?'數量未知':`${p.quantity}份（來源回報）`}</p></div></article>)}</section>}</>}
 {result?.status==='ok'&&!result.stores.length&&<p>來源此次未回報此區域的門市資料；不代表所有門市售完。</p>}
 <Link className="secondary" href="/">返回自營店家與攤販</Link><p><Link href="/privacy/">隱私與資料使用說明</Link></p></main><nav className="bottom-nav" aria-label="主要導覽"><Link href="/">自營店家</Link><Link className="active" href="/convenience/">超商資訊</Link><Link href="/profile/">個人中心</Link></nav></div>;
}
