'use client';
import {useState,useEffect,useCallback} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {Capacitor} from '@capacitor/core';
import {Geolocation} from '@capacitor/geolocation';
import VendorProducts from './VendorProducts';
import Frog from './Frog';
import {MapPin,Heart,Leaf,User,Search,Bell,ChevronRight,ArrowLeft,Navigation,ShoppingBag,Check,Store,Ticket,Star,X,LocateFixed} from 'lucide-react';
import {stores,catalog,DemoState,freshState,expire,remaining,favorite,reserve,changeReservation,review,weekStart,distance} from '../lib/demo';
const Map=dynamic(()=>import('./Map'),{ssr:false,loading:()=> <div className="map-canvas map-loading">地圖載入中…</div>});
const key='foodsave-demo-v1';
const tabs=[{id:'map',name:'探索地圖',icon:MapPin,path:'/'},{id:'favorites',name:'我的收藏',icon:Heart,path:'/favorites/'},{id:'missions',name:'惜食任務',icon:Leaf,path:'/missions/'},{id:'profile',name:'個人中心',icon:User,path:'/profile/'}];
const titles:Record<string,string>={favorites:'我的收藏',missions:'惜食任務',profile:'個人中心',reservations:'我的預約',vendor:'示範商家核銷',notifications:'通知中心',coupons:'我的優惠券'};
export default function FoodApp({screen}:{screen:string}){
 const [state,setState]=useState<DemoState>(freshState),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState('rice'),[query,setQuery]=useState(''),[filter,setFilter]=useState('全部'),[radius,setRadius]=useState(1000),[center,setCenter]=useState<[number,number]>([25.033,121.541]),[located,setLocated]=useState(false),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState(false),[reviewing,setReviewing]=useState(false),[pickup,setPickup]=useState(''),[showIntro,setShowIntro]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const saved=JSON.parse(raw);if(saved.version===1&&Array.isArray(saved.reservations)&&Array.isArray(saved.exp)&&Array.isArray(saved.favorites)&&Array.isArray(saved.notified))setState(expire(saved));}}catch{setMessage('無法讀取先前資料，已使用新的示範紀錄');}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify(state));}catch{setMessage('儲存空間不可用，資料只能保留至離開此頁');}},[state,ready]);
 useEffect(()=>{const t=setInterval(()=>setState(s=>expire(s)),15000);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t);},[message]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setReviewing(false);setExpanded(false);setShowIntro(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
 const products=catalog(state);
 const update=(fn:(s:DemoState)=>DemoState,success:string)=>{try{const next=fn(state);setState(next);setMessage(success);}catch(e){setMessage((e as Error).message);}};
 const choose=useCallback((id:string)=>{setSelected(id);setExpanded(false);setReviewing(false);},[]);
 const store=stores.find(s=>s.id===selected)!;
 const stockProducts=(sid:string)=>products.filter(p=>p.store===sid&&remaining(state,p.id)>0&&(!p.availableUntil||p.availableUntil>Date.now()));
 const visible=stores.filter(s=>distance(...center,s.lat,s.lng)<=radius&&(!query||s.name.includes(query)||products.some(p=>p.store===s.id&&p.name.includes(query)))&&stockProducts(s.id).some(p=>filter==='全部'||p.kind===filter));
 const lifetime=state.exp.reduce((sum,e)=>sum+e.amount,0),weekly=state.exp.filter(e=>e.at>=weekStart()).reduce((sum,e)=>sum+e.amount,0);
 const meters=(s:typeof store)=>distance(...center,s.lat,s.lng);
 async function locate(){setBusy(true);try{let p;if(Capacitor.isNativePlatform()){await Geolocation.requestPermissions();p=await Geolocation.getCurrentPosition({enableHighAccuracy:true,timeout:10000});}else{p=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{timeout:10000}));}setCenter([p.coords.latitude,p.coords.longitude]);setLocated(true);setMessage('已更新搜尋中心；店家仍為示範資料');}catch{setMessage('無法取得位置，可繼續使用台北示範地圖');}finally{setBusy(false);}}
 const nav=(<nav className="bottom-nav" aria-label="主要導覽">{tabs.map(t=><Link key={t.id} href={t.path} className={screen===t.id?'active':''} aria-current={screen===t.id?'page':undefined}><t.icon size={23}/><span>{t.name}</span></Link>)}</nav>);
 const storeCard=(s:typeof store)=> <div className="store-heading"><div className="food-art" style={{background:s.color}}>{s.icon}</div><div className="grow"><h2>{s.name}</h2><p>{s.category}・示範店家</p><span className="distance"><MapPin size={14}/>{meters(s)} 公尺・步行約 {Math.max(1,Math.ceil(meters(s)/75))} 分鐘</span></div></div>;
 const productList=products.filter(p=>p.store===selected&&(!p.availableUntil||p.availableUntil>Date.now())&&(filter==='全部'||p.kind===filter));
 return <div className="app-shell">
 <header className="brand"><Link href="/" className="brand-title"><span className="brand-icon"><Leaf/></span><div>食在可惜<small>好食物・不浪費</small></div></Link><Link href="/notifications/" className="icon-button" aria-label="通知中心"><Bell size={23}/></Link></header>
 <div className="demo-banner"><span className="status-dot"/>核心示範版・店家、庫存及預約皆為本機模擬</div>
 {!ready?<main className="page"><p>正在載入你的惜食紀錄…</p></main>:screen==='map'?<main className="explore">
 <section className="welcome-strip"><div><span className="eyebrow">一起讓美味延續</span><h2>每一份好食物，都值得被珍惜。</h2><p>找附近 → 輕鬆預約 → 步行領取</p><button className="text-button" onClick={()=>setShowIntro(true)}>第一次使用？看 3 個小步驟 <ChevronRight size={16}/></button></div><span className="welcome-leaf" aria-hidden="true"><Frog/></span></section><section className="map-section"><div className="map-toolbar"><div className="search"><Search size={21}/><input placeholder="搜尋店家或商品" aria-label="搜尋店家或商品" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="清除搜尋"><X size={18}/></button>}</div><div className="filters">{['全部','免費','打折','即期'].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'chip chosen':'chip'} aria-pressed={filter===f}>{f}</button>)}<select aria-label="搜尋距離" value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={1000}>1 公里</option><option value={3000}>3 公里</option><option value={5000}>5 公里</option></select></div></div>
 <Map center={center} items={visible.map(s=>({id:s.id,count:stockProducts(s.id).filter(p=>filter==='全部'||p.kind===filter).length}))} onSelect={choose}/>
 <div className="map-footer"><span>{located?'目前 GPS 位置':'台北示範區域'} · {visible.length} 家好店</span><button className="icon-button" onClick={locate} disabled={busy} aria-label="使用目前位置"><LocateFixed size={22}/></button></div></section>
 <section className={'store-sheet '+(expanded?'expanded':'')}><button className="sheet-handle" aria-label={expanded?'收起店家詳情':'展開店家詳情'} onClick={()=>setExpanded(!expanded)} onTouchStart={e=>{e.currentTarget.dataset.y=String(e.touches[0].clientY)}} onTouchEnd={e=>setExpanded(e.changedTouches[0].clientY<Number(e.currentTarget.dataset.y))}><span/></button>
 <div className="nearby-tabs">{visible.map(s=><button key={s.id} className={selected===s.id?'chosen':''} onClick={()=>choose(s.id)}>{s.icon} {s.name}</button>)}</div>
 {!visible.length?<div className="empty"><MapPin/><h2>這裡還沒有示範好店</h2><p>可放寬條件，或回到台北示範區域。</p><button className="primary" onClick={()=>{setCenter([25.033,121.541]);setLocated(false);setQuery('');setFilter('全部');}}>回到示範區域</button></div>:!visible.some(s=>s.id===selected)?<div className="empty"><p>請點選上方店家查看商品。</p></div>:<>
 {storeCard(store)}<p className="intro">{store.intro}</p><div className="store-actions"><button className="secondary favorite-action" aria-pressed={state.favorites.includes(store.id)} onClick={()=>update(s=>favorite(s,store.id),state.favorites.includes(store.id)?'已取消收藏':'已收藏，首次收藏 +50 EXP')}><Heart size={18} fill={state.favorites.includes(store.id)?'currentColor':'none'}/>{state.favorites.includes(store.id)?'已收藏':'收藏店家'}</button><button className="secondary" onClick={()=>setReviewing(!reviewing)}><Star size={18}/>評論 {state.reservations.filter(r=>r.review&&products.find(p=>p.id===r.product)?.store===store.id).length}</button></div>
 <a className="walk-link" href={`https://www.google.com/maps/dir/?api=1&destination=${store.lat},${store.lng}&travelmode=walking`} target="_blank" rel="noreferrer"><Navigation size={17}/>步行前往示範位置 <ChevronRight size={16}/></a>
 {reviewing?<div className="reviews"><button className="text-button" onClick={()=>setReviewing(false)}><ArrowLeft size={16}/>返回商品</button><h3>領取後的真心分享</h3>{state.reservations.filter(r=>r.review&&products.find(p=>p.id===r.product)?.store===store.id).map(r=><article className="card" key={r.id}><b>{'★'.repeat(r.review!.rating)}</b><p>{r.review!.text}</p><small>本機示範評論</small></article>)}<p className="muted">完成示範領取後，可在「我的預約」留下評論。</p></div>:<><div className="section-title"><h3><ShoppingBag size={20}/>本店惜食商品</h3><span>{productList.length} 項</span></div><p className="small muted">示範庫存・每份預約保留 30 分鐘</p><div className="products">{productList.map(p=><article className="product" key={p.id}><div className="product-art">{p.icon}</div><div className="grow"><span className={'tag '+(p.price===0?'free':'')}>{p.kind==='即期'?'即期優惠':p.kind==='免費'?'免費分享':'限時折扣'}</span><h4>{p.name}</h4><p className="small">剩餘 {remaining(state,p.id)} 份</p><div className="price"><del>${p.original}</del><strong>{p.price===0?'免費':`$${p.price}`}</strong></div></div><button className="reserve-button" disabled={remaining(state,p.id)<=0||state.reservations.some(r=>r.product===p.id&&r.status==='waiting')} onClick={()=>update(s=>reserve(s,p.id),'預約成功！請至個人中心 → 我的預約查看取貨碼')}>{state.reservations.some(r=>r.product===p.id&&r.status==='waiting')?'已預約':remaining(state,p.id)<=0?'已售完':'預約 1 份'}</button></article>)}</div></>}
 </>}</section><p className="map-note">地圖底圖需網路；離線時仍可使用示範店家與預約。</p></main>:<main className="page">
 <div className="page-heading">{!tabs.some(t=>t.id===screen)&&<Link href="/profile/" className="icon-button" aria-label="返回個人中心"><ArrowLeft/></Link>}<div><span className="eyebrow">GOOD FOOD, LESS WASTE</span><h1>{titles[screen]}</h1></div></div>
 {screen==='favorites'&&<><p className="page-description">收藏喜歡的店，把美味留在生活裡。</p>{!state.favorites.length?<div className="empty card"><Heart size={42}/><h2>你的惜食口袋名單</h2><p>到地圖收藏第一家好店吧。</p><Link href="/" className="primary">探索附近好店</Link></div>:state.favorites.map(id=>{const s=stores.find(s=>s.id===id)!;return <article className="card" key={id}>{storeCard(s)}<div className="row"><span className="tag">{stockProducts(id).length} 項優惠中</span><button className="text-button" onClick={()=>update(s=>favorite(s,id),'已取消收藏')}>取消收藏</button></div><label className="notify-toggle">優惠通知偏好（本機）<input type="checkbox" checked={state.notified.includes(id)} onChange={()=>setState({...state,notified:state.notified.includes(id)?state.notified.filter(x=>x!==id):[...state.notified,id]})}/></label><Link className="walk-link" href="/">回地圖查看商品 <ChevronRight size={18}/></Link></article>})}</>}
 {screen==='missions'&&<><p className="page-description">小小行動，讓好食物不浪費。</p><div className="exp-card"><span className="leaf-art"><Frog/></span><div><p>本週綠葉經驗值</p><strong>{weekly}<small> EXP</small></strong><p>Lv.{Math.floor(lifetime/500)+1} 惜食新手・累計 {lifetime} EXP</p><progress value={lifetime%500} max={500}/><small>再 {500-lifetime%500} EXP 升級</small></div></div><h2 className="section-heading">今日惜食行動</h2>{[{icon:'🍙',name:'完成一次領取',desc:'預約後，由示範商家驗證取貨碼',exp:100,href:'/reservations/',done:state.reservations.some(r=>r.status==='completed')},{icon:'💚',name:'收藏一家好店',desc:'每家店首次收藏才獲得經驗值',exp:50,href:'/',done:state.favorites.length>0},{icon:'💬',name:'留下真心評論',desc:'每筆完成的領取限評論一次',exp:80,href:'/reservations/',done:state.reservations.some(r=>r.review)}].map(m=><Link className="mission card" key={m.name} href={m.href}><span className="mission-icon">{m.icon}</span><div className="grow"><h3>{m.name}</h3><p>{m.desc}</p><b>+{m.exp} EXP</b></div>{m.done?<Check/>:<ChevronRight/>}</Link>)}<div className="card soft"><h3>🏆 每週排行榜</h3><p>第 1 名 +3 次・第 2–10 名 +2 次<br/>第 11–50 名 +1 次轉盤機會</p><p className="muted">正式排名與週結算尚未串接後端。</p></div><div className="card soft"><h3>🎁 幸運惜食轉盤</h3><p>等待後端抽獎與獎品庫存服務串接。</p><button className="secondary" disabled>尚未開放抽獎</button><p className="small muted">本版不發放真實優惠券或抽獎結果。</p></div></>}
 {screen==='profile'&&<><div className="profile-card"><div className="avatar"><Frog/></div><h2>惜食體驗者</h2><p>一起讓食物有更好的歸宿。</p><span className="tag">Lv.{Math.floor(lifetime/500)+1}・{lifetime} 綠葉 EXP</span></div><div className="quick-links"><Link href="/reservations/"><ShoppingBag/><b>{state.reservations.filter(r=>r.status==='waiting').length}</b>我的預約</Link><Link href="/coupons/"><Ticket/><b>0</b>我的優惠券</Link></div><section className="card menu-list"><Link href="/favorites/"><Heart/>我的收藏<ChevronRight/></Link><Link href="/notifications/"><Bell/>通知中心<ChevronRight/></Link><Link href="/vendor/"><Store/>示範商家核銷<ChevronRight/></Link></section><div className="card soft"><h3>關於此測試版</h3><p>0.1.1 · 資料只存在這台裝置。這不是正式帳號，也不會向真實店家下單。</p><p>正式登入、資料庫、即時庫存及管理後台尚未串接。</p></div></>}
 {screen==='reservations'&&<><p className="page-description">取貨碼只用於本機展示，請勿到真實店家兌換。</p>{!state.reservations.length?<div className="empty card"><ShoppingBag size={40}/><h2>還沒有預約</h2><Link className="primary" href="/">找一份喜歡的美味</Link></div>:[...state.reservations].reverse().map(r=>{const p=r.snapshot??products.find(p=>p.id===r.product)!;return <article className="card reservation" key={r.id}><div className="row"><span className="tag">{{waiting:'等待領取',completed:'已完成',cancelled:'已取消',expired:'已逾時'}[r.status]}</span><small>{r.id}</small></div><h2>{p.icon} {p.name}</h2><p>{stores.find(s=>s.id===p.store)?.name}・1 份・${p.price}</p>{r.status==='waiting'&&<><p className="small">截止：{new Date(r.expires).toLocaleString('zh-TW',{hour12:false})}</p><div className="pickup-code"><small>示範取貨碼</small><strong>{r.code}</strong></div><div className="row"><Link className="primary" href="/vendor/">示範商家核銷</Link><button className="text-button" onClick={()=>update(s=>changeReservation(s,r.id,'cancel'),'已取消預約並恢復示範庫存')}>取消預約</button></div></>}{r.status==='completed'&&(r.review?<p className="review-text">{'★'.repeat(r.review.rating)} {r.review.text}</p>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(s=>review(s,r.id,Number(f.get('rating')),String(f.get('text'))),'評論已儲存，+80 EXP');}}><h3>為這次領取留下評論</h3><label>評分<select name="rating" defaultValue="5"><option value="5">5 星</option><option value="4">4 星</option><option value="3">3 星</option><option value="2">2 星</option><option value="1">1 星</option></select></label><textarea name="text" aria-label="評論內容" placeholder="分享你的惜食體驗" required maxLength={300}/><button className="primary" type="submit">送出評論</button></form>)}</article>})}</>}
 {screen==='vendor'&&<><div className="card soft"><h3>本機商家流程展示</h3><p>正式版本需商家登入及後端驗證權限；這裡示範同裝置的上架、庫存與取貨流程。</p></div><form className="card" onSubmit={e=>{e.preventDefault();const r=state.reservations.find(r=>r.code===pickup&&r.status==='waiting');if(!r){setMessage('找不到此待領取取貨碼');return;}update(s=>changeReservation(s,r.id,'complete',pickup),'核銷成功！完成領取 +100 EXP');setPickup('');}}><label htmlFor="pickup">輸入 6 位示範取貨碼</label><input id="pickup" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="例如 100001" required/><button className="primary" type="submit">確認示範領取</button></form><Link href="/reservations/" className="walk-link">查看預約與領取紀錄<ChevronRight/></Link><VendorProducts state={state} onSave={setState} onMessage={setMessage}/></>}
 {screen==='notifications'&&<><div className="card"><h3>歡迎來到食在可惜 🌱</h3><p>你可以探索示範店家、收藏、預約，再使用取貨碼體驗領取。</p><small>系統說明</small></div>{state.reservations.filter(r=>r.status==='waiting').map(r=><Link href="/reservations/" className="card block" key={r.id}><h3>你有一份美味待領取</h3><p>{products.find(p=>p.id===r.product)?.name}・請在 30 分鐘內完成示範核銷。</p></Link>)}<p className="muted">本版沒有遠端推播，通知由本機預約紀錄產生。</p></>}
 {screen==='coupons'&&<div className="empty card"><Ticket size={44}/><h2>還沒有優惠券</h2><p>抽獎與發券待後端串接，本版不產生可兌換的票券。</p><Link href="/missions/" className="primary">看看惜食任務</Link></div>}
 </main>}
 {showIntro&&<div className="intro-overlay" onClick={()=>setShowIntro(false)}><section className="intro-dialog" role="dialog" aria-modal="true" aria-labelledby="intro-title" onClick={e=>e.stopPropagation()}><span className="welcome-leaf" aria-hidden="true"><Frog/></span><h2 id="intro-title">第一次惜食，從這裡開始</h2><ol><li><b>找附近的好店</b><p>在地圖點綠色圓點，選一份喜歡的食物。</p></li><li><b>預約，留住美味</b><p>每份保留 30 分鐘，取貨碼在「我的預約」。</p></li><li><b>領取，累積綠葉</b><p>本版可在「示範商家核銷」輸入取貨碼，體驗 EXP 與評論。</p></li></ol><p className="small muted">這是本機示範，不會向真實店家下單。</p><button className="primary" autoFocus onClick={()=>setShowIntro(false)}>開始探索好食物</button></section></div>}{message&&<div key={message} className="toast" role="status">{message.startsWith('已收藏')||message.startsWith('核銷成功')?<Frog harvest/>:<Leaf size={20}/>}<span>{message}</span></div>}{nav}</div>;
}
