'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {Capacitor} from '@capacitor/core';
import {Geolocation} from '@capacitor/geolocation';
import {api,Account,ApiError,LiveProduct,Order,liveConfigurationError,utc} from '../lib/api';
import Frog from './Frog';
import PrizeWheel from './PrizeWheel';
import LiveVendor from './LiveVendor';
import PickupCard from './PickupCard';
import {distance} from '../lib/geo';
import {privacyReady} from '../lib/privacy';
const LiveMap=dynamic(()=>import('./LiveMap'),{ssr:false});
const tabs=[['map','探索地圖','/'],['favorites','我的收藏','/favorites/'],['missions','惜食任務','/missions/'],['profile','個人中心','/profile/']];
export default function LiveApp({screen}:{screen:string}){
 const [user,setUser]=useState<Account|null>(null),[products,setProducts]=useState<LiveProduct[]>([]),[favorites,setFavorites]=useState<string[]>([]),[orders,setOrders]=useState<Order[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[signup,setSignup]=useState(false),[center,setCenter]=useState<[number,number]|null>(null),[radius,setRadius]=useState(1000),[selected,setSelected]=useState(''),[reviews,setReviews]=useState<{count:number;average:number|null;items:{rating:number;body:string}[]}|null>(null),[showReviews,setShowReviews]=useState(false),[deleting,setDeleting]=useState(false),[reserved,setReserved]=useState<Order|null>(null);
 const lock=useRef(false),alive=useRef(true);
 const error=useCallback((e:unknown)=>{setMessage(e instanceof Error?e.message:'操作未完成，請重試');if(e instanceof ApiError&&e.status===401)setUser(null);},[]);
 async function refresh(){const [me,p,f,o]=await Promise.all([api.request<Account>('/me'),api.request<LiveProduct[]>('/products'),api.request<string[]>('/favorites'),api.request<Order[]>('/reservations')]);if(alive.current){setUser(me);setProducts(p);setFavorites(f);setOrders(o);}}
 const act=useCallback(async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await fn();}catch(e){error(e);}finally{lock.current=false;if(alive.current)setBusy(false);}},[error]);
 useEffect(()=>{alive.current=true;if(api.authenticated&&!liveConfigurationError)act(refresh);return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!selected||!user)return;let current=true;api.request<typeof reviews>(`/stores/${selected}/reviews`).then(r=>{if(current)setReviews(r);}).catch(error);return()=>{current=false;};},[selected,user?.id]);
 useEffect(()=>{const visible=()=>{if(document.visibilityState==='visible'&&api.authenticated&&!lock.current)act(refresh);};document.addEventListener('visibilitychange',visible);return()=>document.removeEventListener('visibilitychange',visible);},[act]);
 async function locate(){await act(async()=>{try{
  const native=Capacitor.isNativePlatform();
  if(native){const permission=await Geolocation.requestPermissions();if(permission.location!=='granted'&&permission.coarseLocation!=='granted')throw {code:1};}
  if(!native&&!navigator.geolocation)throw {code:2};
  const p=native?await Geolocation.getCurrentPosition({enableHighAccuracy:true,timeout:10000}):await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{timeout:10000}));
  setCenter([p.coords.latitude,p.coords.longitude]);
 }catch(e){setCenter(null);const code=(e as {code?:number|string})?.code;throw new Error(code===1||code==='OS-PLUG-GLOC-0003'?'未允許定位。可到裝置設定開啟權限，仍可瀏覽店家清單。':code===3||code==='OS-PLUG-GLOC-0010'?'定位逾時，請稍後重試；仍可瀏覽店家清單。':'目前無法取得位置，請檢查裝置定位服務；仍可瀏覽店家清單。');}});}

 const stores=Array.from(new Set(products.map(p=>p.store_id))).map(id=>{const p=products.find(p=>p.store_id===id)!;return {id,name:p.store_name,lat:Number(p.latitude),lng:Number(p.longitude),count:products.filter(p=>p.store_id===id&&p.available_quantity>0).length};});
 const visible=stores.filter(s=>(screen!=='favorites'||favorites.includes(s.id))&&(!center||distance(...center,s.lat,s.lng)<=radius));
 const selectedStore=visible.find(s=>s.id===selected)||visible[0];
 function choose(id:string){setSelected(id);setReviews(null);setShowReviews(false);}
 useEffect(()=>{if(!selected&&visible.length)setSelected(visible[0].id);},[products,selected]);
 return <div className="app-shell live-app"><header className="brand"><Link href="/" className="brand-title">食在可惜<small>好食物・不浪費</small></Link><span className="tag">連線模式</span></header><main className="page"><p role="status" className={message?'live-message':''}>{message}</p>{busy&&<p role="status">正在確認資料…</p>}
 {liveConfigurationError?<section className="card"><h1>服務尚未配置</h1><p>{liveConfigurationError}</p><p>不會使用示範資料代替正式服務。</p></section>:!user?<section className="card live-form"><div className="live-frog"><Frog/></div><h1>{signup?'開始你的惜食旅程':'歡迎回來'}</h1><p>登入使用真實帳號。為保護帳號，重開 App 後需要重新登入。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{const email=String(f.get('email')),password=String(f.get('password'));if(signup)await api.request('/auth/register','POST',{email,password});const me=await api.login(email,password);setUser(me);await refresh();});}}><label>電子郵件<input name="email" type="email" autoComplete="username" required/></label><label>密碼（至少12字元）<input name="password" type="password" minLength={12} maxLength={128} autoComplete={signup?'new-password':'current-password'} required/></label>{signup&&<label><input type="checkbox" required/> 我已閱讀<Link href="/privacy/">隱私及帳號刪除說明</Link></label>}<button className="primary" disabled={busy||(signup&&!privacyReady)}>{signup?'建立帳號':'登入'}</button></form>{signup&&!privacyReady&&<p>營運者隱私資料尚未填齊，暫不開放註冊。</p>}<button className="text-button" onClick={()=>setSignup(!signup)}>{signup?'已有帳號？登入':'第一次使用？建立帳號'}</button><Link href="/privacy/">隱私與刪除說明</Link></section>:<>
 {(screen==='map'||screen==='favorites')&&<><section className="welcome-strip"><div><h1>{screen==='favorites'?'我的收藏':'附近的好食物'}</h1><p>每一份收穫，都值得珍惜。</p></div><span className="welcome-leaf"><Frog/></span></section><div className="row"><button className="secondary" onClick={locate}>使用目前位置</button><label>範圍<select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={1000}>1公里</option><option value={3000}>3公里</option><option value={5000}>5公里</option></select></label></div>{center?<LiveMap center={center} stores={visible} onSelect={choose}/>:<p>尚未取得位置，先列出可用店家；允許定位後依距離篩選。</p>}<p className="small muted">地圖底圖需網路；店家與庫存以後端資料為準。</p><div className="nearby-tabs">{visible.map(s=><button key={s.id} onClick={()=>choose(s.id)}>{s.name} · {s.count}項</button>)}</div>{!selectedStore?<div className="empty card"><h2>這裡還沒有可用的好店</h2><p>稍後再來看看，或調整範圍。</p></div>:<section className="card"><h2>{selectedStore.name}</h2><button className="text-button" onClick={()=>setShowReviews(!showReviews)}>{reviews?.average?Number(reviews.average).toFixed(1)+' ★':'尚無評分'} · {reviews?.count||0}則評論</button><div className="row"><button className="secondary" disabled={busy||user.role!=='consumer'} onClick={()=>act(async()=>{await api.mutate(`favorite:${selectedStore.id}`,`/favorites/${selectedStore.id}`,{enabled:!favorites.includes(selectedStore.id)},'PUT');await refresh();setMessage('收藏已更新');})}>{favorites.includes(selectedStore.id)?'取消收藏':'收藏店家'}</button><a className="secondary" href={`https://www.google.com/maps/dir/?api=1&destination=${selectedStore.lat},${selectedStore.lng}&travelmode=walking`} target="_blank" rel="noreferrer">步行導航</a></div>{showReviews?<><button className="text-button" onClick={()=>setShowReviews(false)}>返回商品</button>{reviews?.items.map((r,i)=><article key={i}><p>{'★'.repeat(r.rating)}</p><p>{r.body}</p></article>)}</>:products.filter(p=>p.store_id===selectedStore.id).map(p=><article key={p.id} className="product"><img className="live-food-photo" src={p.photo_url} alt={p.name} loading="lazy"/><div className="grow"><h3>{p.name}</h3><p><del>${p.original_price_minor/100}</del> <b>${p.sale_price_minor/100}</b></p><p>剩餘 {p.available_quantity} 份 · 領取截止 {utc(p.pickup_deadline).toLocaleString('zh-TW')}</p><button className="reserve-button" disabled={busy||p.available_quantity<1||user.role!=='consumer'} onClick={()=>act(async()=>{const result=await api.mutate<Order>(`reserve:${p.id}`,'/reservations',{product_id:p.id,quantity:1});setReserved(result);await refresh();document.getElementById('active-pickup')?.scrollIntoView({block:'center'});setMessage('預約成功，請到我的預約查看取貨碼。');})}>預約1份</button></div></article>)}</section>}</>}
 {screen==='missions'&&(user.role==='consumer'?<><h1>惜食任務</h1><div className="exp-card"><div className="live-frog"><Frog/></div><div><strong>{user.exp} EXP</strong><p>每一次惜食，都留下好影響。</p></div></div><p>EXP 為經驗值，不是真錢。活動與獎勵依已開放設定。</p><PrizeWheel spins={user.spins} onResult={()=>{setMessage('');refresh().catch(error);}} onError={error}/></>:<p>抽獎供消費者帳號使用。</p>)}
 {reserved&&screen==='map'&&<section id="active-pickup" className="card"><h2>已為你保留1份</h2><PickupCard order={reserved}/><Link href="/reservations/" className="secondary">查看／取消預約</Link></section>}
 {screen==='profile'&&<><h1>個人中心</h1><div className="card"><p>{user.email}</p><p>{({consumer:'惜食用戶',vendor:'合作商家',admin:'管理員'})[user.role]}</p><Link className="primary" href="/reservations/">我的預約</Link>{user.role==='vendor'&&<Link className="secondary" href="/vendor/">商家工作台</Link>}{user.role==='admin'&&<a className="secondary" href={api.base+'/admin'} target="_blank" rel="noreferrer">管理中心</a>}</div><button className="secondary" onClick={()=>act(async()=>{await api.logout();setUser(null);setProducts([]);setOrders([]);})}>登出</button><p><Link href="/privacy/">隱私與帳號刪除</Link></p><button className="text-button" onClick={()=>setDeleting(!deleting)}>申請刪除帳號</button>{deleting&&<form className="card live-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{await api.request('/account/deletion-requests','POST',{password:String(f.get('password')),confirm:'DELETE'});api.clear();setUser(null);setSignup(false);setMessage('已收到刪除申請並停用帳號。資料刪除仍待管理者依保存政策處理，尚未完成抹除。');});}}><p>送出後立即停用帳號並撤銷登入。既有預約請先取消；資料最終移除須依營運者保存政策處理。</p><label>再次輸入密碼<input name="password" type="password" minLength={12} required autoComplete="current-password"/></label><label><input type="checkbox" required/> 我確認申請刪除並停用帳號</label><button className="primary" disabled={busy}>確認送出刪除申請</button></form>}</>}
 {screen==='reservations'&&<><h1>我的預約</h1><button className="secondary" onClick={()=>act(refresh)}>重新確認預約</button>{orders.length===0&&<p>目前沒有預約。</p>}{orders.map(o=>{const p=typeof o.snapshot==='string'?JSON.parse(o.snapshot):o.snapshot;return <article key={o.id} className="card"><span className="tag">{({waiting:'等待領取',completed:'已完成',cancelled:'已取消',expired:'已逾時'} as Record<string,string>)[o.state]}</span><h2>{p.name}</h2><p>{o.quantity}份 · ${p.sale_price_minor/100}</p><p>截止 {utc(o.expires_at).toLocaleString('zh-TW')}</p>{o.state==='waiting'&&<><PickupCard order={o}/><button className="secondary" disabled={busy} onClick={()=>act(async()=>{await api.mutate(`cancel:${o.id}`,`/reservations/${o.id}/cancel`,{});await refresh();setMessage('預約狀態已更新');})}>取消預約</button></>}{o.state==='completed'&&<form className="live-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{await api.mutate(`review:${o.id}`,`/reservations/${o.id}/review`,{rating:Number(f.get('rating')),body:String(f.get('body'))});setMessage('評論已儲存');await refresh();});}}><label>評分<select name="rating">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n}星</option>)}</select></label><label>評論<textarea name="body" required maxLength={1000}/></label><button className="primary" disabled={busy}>送出評論</button></form>}</article>;})}</>}
 {screen==='vendor'&&(user.role==='vendor'?<LiveVendor act={act} onError={error}/>:<p>此頁需要商家帳號。</p>)}
 {screen==='coupons'&&<p>請到惜食任務查看後端獲獎與優惠券紀錄。</p>}{screen==='notifications'&&<p>目前未啟用推播通知，請從我的預約確認領取狀態。</p>}
 </>}</main><nav className="bottom-nav" aria-label="主要導覽">{tabs.map(([id,label,href])=><Link key={id} href={href} className={screen===id?'active':''}>{label}</Link>)}</nav></div>;
}
