'use client';
import {useEffect,useState} from 'react';
import {api,LiveProduct,Order,utc} from '../lib/api';
type Catalog={stores:{id:string;name:string}[];products:LiveProduct[]};
export default function LiveVendor({act,onError}:{act:(f:()=>Promise<void>)=>void;onError:(e:unknown)=>void}){
 const [catalog,setCatalog]=useState<Catalog>({stores:[],products:[]}),[orders,setOrders]=useState<Order[]>([]),[edit,setEdit]=useState<LiveProduct|null>(null),[notice,setNotice]=useState('');
 async function refresh(){const [c,o]=await Promise.all([api.request<Catalog>('/vendor/catalog'),api.request<Order[]>('/vendor/reservations')]);setCatalog(c);setOrders(o);}
 useEffect(()=>{refresh().catch(onError);},[]);
 return <section><h2>商家工作台</h2><p>所有商品與領取狀態由後端確認。</p><button className="secondary" onClick={()=>act(refresh)}>重新載入商家資料</button><p role="status">{notice}</p>{catalog.stores.length===0?<p>尚未有分配給此帳號的店家，請聯絡管理者。</p>:<form key={edit?.id||'new'} className="card live-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{const body={store_id:String(f.get('store_id')),name:String(f.get('name')),photo_url:String(f.get('photo_url')),original_price_minor:Math.round(Number(f.get('original'))*100),sale_price_minor:Math.round(Number(f.get('sale'))*100),available_quantity:Number(f.get('quantity')),pickup_deadline:new Date(String(f.get('deadline'))).toISOString(),active:f.get('active')==='on',revision:edit?.revision||1};await api.mutate(`product:${edit?.id||'new'}`,edit?`/vendor/products/${edit.id}`:'/vendor/products',body,edit?'PUT':'POST');setNotice('商品已儲存');setEdit(null);await refresh();});}}><h3>{edit?'編輯商品':'上架商品'}</h3><label>店家<select name="store_id" defaultValue={edit?.store_id}>{catalog.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>商品名稱<input name="name" required maxLength={160} defaultValue={edit?.name}/></label><label>已授權商品照片網址<input name="photo_url" type="url" required pattern="https://.*" defaultValue={edit?.photo_url}/></label><label>原價（元）<input name="original" type="number" min="0" step="0.01" required defaultValue={edit?edit.original_price_minor/100:undefined}/></label><label>惜食價（元）<input name="sale" type="number" min="0" step="0.01" required defaultValue={edit?edit.sale_price_minor/100:undefined}/></label><label>可預約庫存<input name="quantity" type="number" min="0" step="1" required defaultValue={edit?.available_quantity}/></label><label>領取截止<input name="deadline" type="datetime-local" required defaultValue={edit?new Date(utc(edit.pickup_deadline).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):undefined}/></label><label><input name="active" type="checkbox" defaultChecked={edit?.active??true}/> 開放預約</label><button className="primary">儲存商品</button>{edit&&<button type="button" className="secondary" onClick={()=>setEdit(null)}>取消編輯</button>}</form>}
 <h3>我的商品</h3>{catalog.products.map(p=><article className="card" key={p.id}><h3>{p.name}</h3><p>剩餘 {p.available_quantity} 份 · ${p.sale_price_minor/100}</p><button className="secondary" onClick={()=>setEdit(p)}>編輯 {p.name}</button></article>)}<h3>店家預約</h3>{orders.map(o=><article className="card" key={o.id}><p>{o.id}</p><p>{({waiting:'待領取',completed:'已領取',cancelled:'已取消',expired:'已逾時'} as Record<string,string>)[o.state]} · {o.quantity}份</p>{o.state==='waiting'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{const result=await api.mutate<{state:string}>(`complete:${o.id}`,`/vendor/reservations/${o.id}/complete`,{code:String(f.get('code')).toUpperCase()});setNotice(result.state==='completed'?'核銷成功':'此預約已逾時，庫存已返還');await refresh();});}}><label>取貨碼<input name="code" required pattern="[a-fA-F0-9]{12}" maxLength={12}/></label><button className="primary">確認領取</button></form>}</article>)}</section>;
}
